### ISSUE TITLE
How to use this utility for compound nodes

### ISSUE THREAD

**Issue by Does666** [iVis-at-Bilkent/cytoscape.js-layout-utilities#17]
How should I use this utility for compound nodes ? 
When use layout `cose-bilkent` with `tile` true,  the disconnected nodes which maybe have parent node or not,  will be tiled together,  but sometimes the disconnected nodes maybe layout far away from the connected nodes.  Is this utility effective for such case ?

> Notice that in case you make use of compound nodes, it's sufficient to pass only highest level (root) nodes in the nesting hierarchy.

I read this sentence from the description of this tool.  Does it mean `cy.elements(":visible[^parent]").components()` ?

**Comment by hasanbalci** [comment]
@Does666 This utility, with its current status, isn't effective for your case. Its main aim is to pack top level components. Applying it to components in a parent node has some side effects:
- Since the extension doesn't currently accept a bounding box to pack components, the resulting shift amounts may move components to origin (0, 0), so you may need to move them again to the position where the parent node is located after layout. 
- Packing components in a parent node after layout may decrease the quality of the layout, because it may cause lots of empty space around the parent node after packing.

By the way, Cytoscape's `eles.components()` function is not good at finding components that contain compound nodes, it requires extra work generally.

**Comment by hasanbalci** [comment]
@Does666 To solve your problem, you can adjust `gravityCompound` and `gravityRangeCompound` options in the `cose-bilkent` layout according to your needs. `gravityCompound` controls the gravitational force that is applied to attract disconnected nodes inside a compound to their center. You can increase this value to increase the gravitational force. `gravityRangeCompound` option controls the range where gravitational force is not applied in a compound node. Decreasing this value can also work for you. To sum up, I suggest you increasing `gravityCompound` and decreasing `gravityRangeCompound` values.
