### ISSUE TITLE
Error when polyomino grid size factor is less than 1

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/cytoscape.js-layout-utilities#20]
It can be seen in the demo that setting polyomino grid size factor to a value less than 1 throws error in the console.

**Comment by onsah** [comment]
The issue is related to these lines:
 https://github.com/iVis-at-Bilkent/cytoscape.js-layout-utilities/blob/66d44a6852608a18b3017d0b305b9bd6ead77f57/demo.html#L283-L284
`parseInt` function parse the number to an integer so that entering 0.5 yields 0 which causes some problems. Changing the line about grid size factor fixes the problem. But also desired aspect ratio wasn't functioning properly because it also used `parseInt`. So when one enters 0.5 it was actually aiming to get 0 aspect ratio.

**Comment by ugurdogrusoz** [comment]
@onsah Could you please fix this in the unstable branch? Make sure to refer to the issue in your commit.

**Comment by onsah** [comment]
Comitted the changes to the unstable branch. 

Unfortunately I pushed without mentioning the issue then I committed the same changes with different commit message referring to the issue. So there is two of the same commit in the commit history hopefully that is not a problem.

**Comment by hasanbalci** [comment]
@onsah Next time when you forget referencing the issue in your commit, add a comment to the issue that references the commit.
