### ISSUE TITLE
Incremental packing

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-layout-utilities#21]
When a graph is laid out and its components are packed, we get a nice compact layout of disconnected graphs. However, if some minor changes are made to the graph topology (e.g. adding some neighbors to one of the nodes), then the packing is not done incrementally when layout is done incrementally. If the layout is done non-incrementally, the user loses their mental map o the graph. So, let's see if we can find a way to make the current polyomino packing algorithm work incrementally.

**Comment by hasanbalci** [comment]
Some notes about code:
- According to [here](https://github.com/iVis-at-Bilkent/cytoscape.js-layout-utilities/blob/151d80a6151450357f3bfd3ce3277f562d8ec490/src/core/layout-utilities.js#L373), incremental packing is applied when `incremental` option is false. It should be the opposite.
- When I set `componentSpacing` option to a smaller value, e.g. 10, and apply incremental packing in demo, it cannot finish the packing, maybe enters to an infinite loop.

Some notes about demo page:
- Result fullness is not written correctly when incremental packing is applied. For example, it should be 69% instead of 0.69%.
- I think Auto checkbox near the Component Spacing field is for setting `componentSpacing` option as `undefined` during incremental packing so that the algorithm calculates spacing automatically. It should be disabled while incremental checkbox is unchecked, but it seems as enabled on page load.
- It will be nice if a spacing can be added between Component Spacing input field and "Auto" text.

**Comment by ugurdogrusoz** [comment]
- Should we perhaps rename `incremental` as `randomize` to be consistent with other extensions (and also not having to change functionality)? If so, when randomize is false, we should do it incrementally.

**Comment by hasanbalci** [comment]
It makes sense.

**Comment by onsah** [comment]
Renamed the `incremental` to `randomize` and changed the README according to it. And  I will fix the problems with the demo page.

For the problem about `componentSpacing` I checked and @hasanbalci is right that it enters an inifinite loop. Right now termination is done when no components are overlapping and average force is less than `CONVERGENCE_THRESHOLD`. But right now this value is a constant. However, using a constant is not feasible for all `componentSpacing` values because:
https://github.com/iVis-at-Bilkent/cytoscape.js-layout-utilities/blob/9a43232fa260cdcffcf66056d3d304ad0888d920/src/pose/embedder/basic-embedder.ts#L31
https://github.com/iVis-at-Bilkent/cytoscape.js-layout-utilities/blob/9a43232fa260cdcffcf66056d3d304ad0888d920/src/pose/embedder/basic-embedder.ts#L33
and https://github.com/iVis-at-Bilkent/cytoscape.js-layout-utilities/blob/9a43232fa260cdcffcf66056d3d304ad0888d920/src/pose/embedder/basic-embedder.ts#L11

The forces depend upon `componentSpacing` and thus the trheshold should also depend on it to scale. I think threshold should be proportional to `1/componentSpacing` because when component spacing gets lower, the attractive force become larger. I guess the repulsive force should always decrease because it is only calculated between components with no edges and the force is always in the same direction therefore we can ignore it for determining the `CONVERGENCE_THRESHOLD`. 

What do you think? How exactly the `CONVERGENCE_THRESHOLD` should be calculated?

**Comment by ugurdogrusoz** [comment]
How about simply having a max iteration count? (no components are overlapping and average force is less than CONVERGENCE_THRESHOLD) or (iteration greater than max iteration count)
This is simple enough and should work. You could determine this count empirically by checking how many iterations it takes say to incrementally pack a graph with around 20 components.

**Comment by onsah** [comment]
I tried with around 20 components and set the iteration count to 100.

I tested the demo further and found that in some cases the intersection force is balanced by the other forces therefore the algorithm may never manage to separate the components. To fix this problem I gave intersection forces priority over other forces.

All chanags are in the da6e52a1cfb8bf303cb73f94f5aee63f681e258c commit

**Comment by ugurdogrusoz** [comment]
@hasanbalci Can we please test this again?

**Comment by hasanbalci** [comment]
I merged the incremental packing functionality to the unstable branch and now it can be tested comprehensively via layouts. However, it seems that its performance should be improved because it takes about 3 seconds for 24 components in my tests. So, I keep this issue open for now.

**Comment by ugurdogrusoz** [comment]
Performance related problems are now addressed in a separate issue, closing this.
