### ISSUE TITLE
Demo related issues

### ISSUE THREAD

**Issue by PermanAtayev** [iVis-at-Bilkent/cytoscape.js-layout-utilities#8]
- [x] 1. "Shift + taphold" seems to be not working, and also it's a bit confusing term, what does it exactly mean?
- [x] 2. In the "pack components" section of the website, it might be a good idea to rearrange the order of the entries. And maybe creating a button to "pack components" rather than to use the title as a button would be more user-friendly.
- [x] 3. In the "pack components" section, it would also be good to either hide or specify "Result" fields as empty before "pack components" was applied.

**Comment by ugurdogrusoz** [comment]
1. taphold means click and hold. this used to select the neighbors of the node as specified. let's check if it can be easily restore; otherwise get rid of it.
2. extension demos are not very good/rich at the moment but let's not spend time on this. may be if there is a quick way to make them look like action items.
3. we could use "-" (dashes) when no value is available.

**Comment by ugurdogrusoz** [comment]
@PermanAtayev please review and close if also ok with you

**Comment by PermanAtayev** [comment]
It seems good!
